name: battocchiozinni
entrypoint: python3 exp_runner.py --mode train --conf ./confs/thin_structure.conf --case chair_raw

resources:
   slots_per_trial: 1

bind_mounts:
  - host_path: /media/mmlab/Volume/battocchiozinni/NeuS_data/
    container_path: /media/dataset
    read_only: true
  - host_path: /home/battocchiozinni/Documents
    container_path: /media/checkpoint
    read_only: false

searcher:
  name: single
  metric: accuracy
  max_length: 1
  
max_restarts: 0

# det -m 10.196.36.18:8080 trial logs -f 1009